version: '3.5'
services:
  fpm:
      image: tomhjx/php:fpm.centos7.7.4.9.20201118
      restart: always
      volumes:
        - ~/Work:/work
      cap_add:
        - ALL
      environment:
        COMPOSER_PROCESS_TIMEOUT: 3000
        COMPOSER_MEMORY_LIMIT: -1
networks:
  default:
    name: lab